// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcQgqDw5mBGYTI1XtRoFGXadob_Sa8hc',
    appId: '1:375450566619:web:3373186687fb0359e231fe',
    messagingSenderId: '375450566619',
    projectId: 'cems-application',
    authDomain: 'cems-application.firebaseapp.com',
    storageBucket: 'cems-application.firebasestorage.app',
    measurementId: 'G-KXKYNHHZHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5qwLUgyDe0ZIslkfR_5rv3JdxdSnDM8M',
    appId: '1:375450566619:android:8c62cc78672f5b46e231fe',
    messagingSenderId: '375450566619',
    projectId: 'cems-application',
    storageBucket: 'cems-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiGn38x74_q9o9rY2FofM4WETsZlWgmHs',
    appId: '1:375450566619:ios:dc1ba2a8fb4c5bc9e231fe',
    messagingSenderId: '375450566619',
    projectId: 'cems-application',
    storageBucket: 'cems-application.firebasestorage.app',
    iosBundleId: 'com.example.cemsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiGn38x74_q9o9rY2FofM4WETsZlWgmHs',
    appId: '1:375450566619:ios:dc1ba2a8fb4c5bc9e231fe',
    messagingSenderId: '375450566619',
    projectId: 'cems-application',
    storageBucket: 'cems-application.firebasestorage.app',
    iosBundleId: 'com.example.cemsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGcQgqDw5mBGYTI1XtRoFGXadob_Sa8hc',
    appId: '1:375450566619:web:d2b1c270ff3fbf4ee231fe',
    messagingSenderId: '375450566619',
    projectId: 'cems-application',
    authDomain: 'cems-application.firebaseapp.com',
    storageBucket: 'cems-application.firebasestorage.app',
    measurementId: 'G-E1GJJLP9YP',
  );
}
